### ISSUE TITLE
file not found: #import "CDVWKWebViewUIDelegate.h" with  cordova-plugin-ionic-webview

### ISSUE THREAD

**Issue by kbrin423** [dpa99c/cordova-plugin-inappbrowser-wkwebview#1]
Hi !
I develop an ionic application and i just installed the WKWebViewPlugin: ( cordova-plugin-ionic-webview
![capture d ecran 2017-10-11 a 15 29 37](https://user-images.githubusercontent.com/9021128/31443758-a5018bd2-ae9a-11e7-8fd7-e028ef5d2f57.png)
 ) and i need to shared coockies with my webview.

Your plugin depends on cordova-plugin-wkwebview-engine but for using cordova-plugin-ionic-webview i deleted it.

My error: 

file not found
    #import "CDVWKWebViewUIDelegate.h"

=> I can't installed cordova-plugin-wkwebview-engine because i have: duplicate symbol _OBJC_IVAR_$_CDVWKWebViewEngine._engineWebView 

THX! :)

**Comment by dpa99c** [comment]
This plugin has been developed and tested against `cordova-plugin-wkwebview-engine`. If you are using the Ionic version instead, that is not something I have tested, so unsure if it will work. However, there's no hard-coded dependency that installs `cordova-plugin-wkwebview-engine`.

FWIW regarding your error message, it seems that file [does exist](https://github.com/ionic-team/cordova-plugin-ionic-webview/blob/master/src/ios/CDVWKWebViewUIDelegate.h) also in the Ionic version, so what probably happened is that when you uninstalled `cordova-plugin-wkwebview-engine`, it removed these source files from the iOS platform project since it also adds them.

You can try this:
- remove `cordova-plugin-wkwebview-engine` if installed
- remove the iOS platform: `cordova platform rm ios`
- make sure this plugin and Ionic WKWebView are installed
- re-add the iOS platform: `cordova platform add ios`

This should give you an iOS platform project with this plugin and the Ionic WKWebView present.
Still no guarantees it will work though - as I said, it has only been tested with the Cordova version.

**Comment by kbrin423** [comment]
it works ! thx 👍 

ionic 3.13.0 with cordova-plugin-ionic-webview
