### ISSUE TITLE
Got logged out of app when using _system as target

### ISSUE THREAD

**Issue by agnosco** [dpa99c/cordova-plugin-inappbrowser-wkwebview#2]
when I use target as '_system', it opens the url and when I click on back I redirects to login screen but works fine with target '_blank'. Is it a desired behavior?

thank you!

**Comment by dpa99c** [comment]
I'm unsure what you mean by this.

When you set `_system` as the target, the page is opened in the system browser app which in the case of iOS is the Safari app. From this point, any handling of login state takes place in the Safari app and has nothing to do with this plugin.

Can you explain exactly what the problem is, ideally with steps or an example that can be used to reproduce the problem?

**Comment by agnosco** [comment]
I'm logged in my ios app and have an external link in the app. So, to open the link in safari I have cordova.InAppBrowser.open(url, '_system', 'location=no');". It opens the url link in safari but I get logged out from app when I tried to go back to app.

**Comment by dpa99c** [comment]
When you open the Safari app, your app is put into the background. If the iOS device has enough memory, your app will be suspended so when you return to your app it will be resumed. However, if the iOS device is low on memory, it may decide to terminate your app process when it enters the background, which means when you "go back" to your app, your app is actually being started again. This may lead you to lose your login session if you haven't somehow persisted the session in local device storage.

All of this is unrelated to the function of this plugin. Indeed, this is a fork of the [official Cordova InappBrowser plugin](https://github.com/apache/cordova-plugin-inappbrowser) and no code changes have been made to the interaction with the system browser (i.e. Safari). To convince yourself of this, you should try repeating your test with the official Cordova version of [cordova-plugin-inappbrowser](https://github.com/apache/cordova-plugin-inappbrowser) and observe that it results in the same behaviour as if you used this fork of the plugin. The only difference between this plugin and the official one is the the "in-app browser" Webview (invoked by `target=_blank`) is powered by WKWebView instead of UIWebView.

**Comment by agnosco** [comment]
Yes, it's the same with cordova-plugin-inappbrowser. Thank you for making it clear.

**Comment by Yuripetusko** [comment]
@agnosco I am having the same problem, but not sure why yet, looks like if url has https:// then i get this effect - when system browser opens it reloads the main view so when i come back it is all reset, and weirdly cookies are also deleted so user gets logged out. Did you find out the reason for this?
