### ISSUE TITLE
Problem clearing cache and session

### ISSUE THREAD

**Issue by nishanthvincent** [dpa99c/cordova-plugin-inappbrowser-wkwebview#3]
Thanks so much for this plugin

Here's something I found and any solution on this would be really appreciated

When I open a new instance I pass in the following arguments
$cordovaInAppBrowser.open('URL', '_blank', {
        location: 'yes',
        toolbar: 'yes',
        hidenavigationbuttons: 'no',
        clearcache: 'yes',
        clearsessioncache: 'yes',
        enableViewportScale: 'yes'
      });
Current behaviour: It retains cookie information from previous sessions
Desired behaviour: clear out cache everytime this browser window opens

**Comment by dpa99c** [comment]
[This plugin is using](https://github.com/dpa99c/cordova-plugin-inappbrowser-wkwebview/blob/master/src/ios/CDVInAppBrowser.m#L591) a [WKProcessPool](https://developer.apple.com/documentation/webkit/wkprocesspool?language=objc) via [CDVWKProcessPoolFactory](https://github.com/apache/cordova-plugin-wkwebview-engine/blob/master/src/ios/CDVWKProcessPoolFactory.m) in [cordova-plugin-wkwebview-engine](https://github.com/apache/cordova-plugin-wkwebview-engine) to share cookies between the main Cordova WKWebView and the InappBrowser WKWebView instances.

Hence [the current cookie clearing behaviour](https://github.com/dpa99c/cordova-plugin-inappbrowser-wkwebview/blob/master/src/ios/CDVInAppBrowser.m#L126) ported across from `cordova-plugin-inappbrowser` is not working because that's intended for UIWebView.

The plugin needs updating to use a WKWebView-specific method of clearing cookies in the shared process pool, such as the one [outlined in this SO answer](https://stackoverflow.com/a/31803708/777265).

**Comment by nishanthvincent** [comment]
Thanks for your reply.  Is there a time line you have for this fix ?
